spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/data/fxrates
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create